version: "3.8"
services:
  postgresDB:
    image: postgres:13.15-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contack_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
